# Netlify "kitchen sink" example: https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml
backend:
  name: git-gateway
  branch: master

localhost_development:
  backend:
    name: file-system
    api_root: /api

display_url: http://localhost:8000
media_folder: static/assets
public_folder: assets
publish_mode: editorial_workflow

collections:
  - name: mdx
    label: Mdx Example
    description: Documentation
    folder: content/mdx
    extension: mdx
    format: frontmatter
    widget: mdx
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Body, name: body, widget: mdx }

  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: blog-post,
        }
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: text }
      - { label: Tags, name: tags, widget: list }
      - { label: Body, name: body, widget: markdown }
