backend:
    name: github
    repo: hppRC/hppPortfolio
    branch: master

media_folder: static/assets
public_folder: assets
publish_mode: editorial_workflow

collections:
    - name: posts
      label: Posts
      folder: posts
      create: true
      fields:
          - { name: slug, label: Slug, widget: string }
          - { name: date, label: Date, widget: datetime }
          - { name: title, label: Title, widget: string }
          - { name: tags, label: Tags, widget: list }
          - { name: cover, label: Cover, widget: image }
          - { name: body, label: Body, widget: markdown }
